app:
  redis:
    session:
      timeout: 15
lang: en
server:
  port: ${PORT:9000}
spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: false
    database: postgresql
  redis:
    host: localhost
    port: 6379